version: '3'
services:
  client:
    image: openfoam-client
    stdin_open: true
    ports:
      - "8080:8080"
    networks:
      - app
  server:
    image: openfoam-server
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app
networks:
  app:
    driver: bridge
